"""Tests for chargeback_contracts.recommendation."""

from datetime import UTC, datetime

import pytest
from chargeback_contracts.recommendation import (
    InvestigationRecommendation,
    MissingCapabilityWarning,
    RecommendationType,
)
from chargeback_contracts.skills import SkillId
from pydantic import ValidationError


def _valid_warning(**overrides: object) -> MissingCapabilityWarning:
    defaults: dict[str, object] = {
        "required_skill_id": SkillId.DUPLICATE_TRANSACTION_INVESTIGATION,
        "message": "Duplicate-transaction specialist is not yet registered.",
        "can_continue_partially": True,
        "affected_area": "duplicate transaction check",
        "discovered_at": datetime(2026, 1, 1, tzinfo=UTC),
    }
    defaults.update(overrides)
    return MissingCapabilityWarning(**defaults)  # type: ignore[arg-type]


def _valid_recommendation(**overrides: object) -> InvestigationRecommendation:
    defaults: dict[str, object] = {
        "investigation_id": "INV-1",
        "recommendation": RecommendationType.REQUEST_MORE_EVIDENCE,
        "reason_codes": ("MISSING_DELIVERY_PROOF",),
        "explanation": "Delivery proof has not yet been provided by the merchant.",
        "generated_at": datetime(2026, 1, 1, tzinfo=UTC),
    }
    defaults.update(overrides)
    return InvestigationRecommendation(**defaults)  # type: ignore[arg-type]


def test_recommendation_type_stable_values() -> None:
    assert RecommendationType.ACCEPT_CHARGEBACK.value == "accept_chargeback"
    assert RecommendationType.REJECT_CHARGEBACK.value == "reject_chargeback"
    assert RecommendationType.REQUEST_MORE_EVIDENCE.value == "request_more_evidence"


def test_valid_recommendation_round_trips_through_json() -> None:
    recommendation = _valid_recommendation()
    restored = InvestigationRecommendation.model_validate_json(recommendation.model_dump_json())
    assert restored == recommendation


def test_missing_capability_warning_round_trips_through_json() -> None:
    warning = _valid_warning()
    restored = MissingCapabilityWarning.model_validate_json(warning.model_dump_json())
    assert restored == warning


def test_reason_codes_must_be_non_empty() -> None:
    with pytest.raises(ValidationError):
        _valid_recommendation(reason_codes=())


def test_explanation_independent_of_recommendation_fields() -> None:
    # Constructed through the normal constructor (not model_copy, which skips
    # validators) so this genuinely proves the fields aren't coupled by any
    # validation logic, not just that two dict keys differ.
    a = _valid_recommendation(explanation="Original explanation.")
    b = _valid_recommendation(explanation="Regenerated by an LLM.")
    assert a.recommendation == b.recommendation
    assert a.reason_codes == b.reason_codes
    assert a.explanation != b.explanation


def test_recommendation_independent_of_explanation() -> None:
    # The reverse direction: same explanation, different deterministic
    # recommendation/reason_codes — both must construct validly.
    a = _valid_recommendation(
        recommendation=RecommendationType.ACCEPT_CHARGEBACK,
        reason_codes=("EVIDENCE_SUPPORTS_CUSTOMER",),
        explanation="Shared explanation text.",
    )
    b = _valid_recommendation(
        recommendation=RecommendationType.REJECT_CHARGEBACK,
        reason_codes=("EVIDENCE_SUPPORTS_MERCHANT",),
        explanation="Shared explanation text.",
    )
    assert a.explanation == b.explanation
    assert a.recommendation != b.recommendation
    assert a.reason_codes != b.reason_codes


def test_rejects_unknown_field() -> None:
    with pytest.raises(ValidationError):
        _valid_recommendation(unexpected_field="nope")


def test_warning_rejects_naive_discovered_at() -> None:
    with pytest.raises(ValidationError, match="timezone-aware"):
        _valid_warning(discovered_at=datetime(2026, 1, 1))  # noqa: DTZ001
