"""Missing-capability and recommendation contracts.

`recommendation` and `reason_codes` on InvestigationRecommendation are
deterministic outputs; `explanation` is descriptive text that may later be
generated by an LLM. Changing the explanation must never require changing
the deterministic fields — they are independent fields, not derived from
one another.
"""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum

from pydantic import Field, ValidationInfo, field_validator

from chargeback_contracts.common import ContractModel, require_non_blank, require_utc
from chargeback_contracts.evidence import EvidenceType
from chargeback_contracts.skills import SkillId


class MissingCapabilityWarning(ContractModel):
    """Explicit representation of an unavailable skill — never a generic exception."""

    required_skill_id: SkillId
    message: str = Field(min_length=1)
    can_continue_partially: bool
    affected_area: str = Field(min_length=1)
    discovered_at: datetime

    @field_validator("message", "affected_area")
    @classmethod
    def _non_blank(cls, value: str, info: ValidationInfo) -> str:
        assert info.field_name is not None
        return require_non_blank(value, field_name=info.field_name)

    @field_validator("discovered_at")
    @classmethod
    def _discovered_at(cls, value: datetime) -> datetime:
        return require_utc(value, field_name="discovered_at")


class RecommendationType(StrEnum):
    """The only supported investigation recommendation outcomes."""

    ACCEPT_CHARGEBACK = "accept_chargeback"
    REJECT_CHARGEBACK = "reject_chargeback"
    REQUEST_MORE_EVIDENCE = "request_more_evidence"


class InvestigationRecommendation(ContractModel):
    """The deterministic recommendation produced for an investigation."""

    investigation_id: str = Field(min_length=1)
    recommendation: RecommendationType
    reason_codes: tuple[str, ...] = Field(min_length=1)
    supporting_finding_ids: tuple[str, ...] = ()
    missing_evidence: tuple[EvidenceType, ...] = ()
    missing_capability_warnings: tuple[MissingCapabilityWarning, ...] = ()
    policy_references: tuple[str, ...] = ()
    explanation: str = Field(min_length=1)
    generated_at: datetime

    @field_validator("investigation_id", "explanation")
    @classmethod
    def _non_blank(cls, value: str, info: ValidationInfo) -> str:
        assert info.field_name is not None
        return require_non_blank(value, field_name=info.field_name)

    @field_validator("generated_at")
    @classmethod
    def _generated_at(cls, value: datetime) -> datetime:
        return require_utc(value, field_name="generated_at")
